model:
  name: "BAAI/bge-small-en-v1.5"
  vector_size: 384
  # name: "all-MiniLM-L6-v2"
  # vector_size: 384
  prefix:
    indexing: ""
    # querying: null
    querying: "Represent this sentence for searching relevant passages: "
mongodb:
  host: "mongodb+srv://root:<password>@changelog.0f5lgie.mongodb.net/?retryWrites=true&w=majority"
  server_api: "1"
  port: 27017
  collection: "docs"
  index_id: "my-index"
indexing:
  transcript_repo_directory: "./transcripts"
  transcript_git_url: "https://github.com/thechangelog/transcripts"
  podcasts:
    - news
    - friends
    - practicalai
    - podcast
    - shipit
    - gotime
    - jsparty
    # - brainscience
    # - backstage
    # - founderstalk
    # - afk
    # - bigtent
    # - rfc
    # - spotlight
api:
  origins:
    - http://localhost:3000
    - https://thechangelogchat.vercel.app
    - https://changelog.duarteocarmo.com

