model:
  # name: "BAAI/bge-base-en"
  # vector_size: 768
  name: "all-MiniLM-L6-v2"
  vector_size: 384
  prefix:
    indexing: ""
    querying: ""
mongodb:
  host: "mongodb+srv://root:<password>@thechangelog.l2qgplu.mongodb.net/?retryWrites=true&w=majority"
  server_api: "1"
  port: 27017
  collection: "docs"
  index_id: "my-index"
indexing:
  transcript_repo_directory: "./transcripts"
  transcript_git_url: "https://github.com/thechangelog/transcripts"
  podcasts:
    - news
    - friends
    # - brainscience
    # - practicalai
    # - shipit
    # - podcast
    # - gotime
    # - backstage
    # - founderstalk
    # - afk
    # - bigtent
    # - jsparty
    # - rfc
    # - spotlight
api:
  origins:
    - "http://localhost:3000"
