version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8000"
    restart: always
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
